apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  selector:
    matchLabels:
      label: web-project
  replicas: 3
  template:
    metadata:
      name: os-project
      labels:
        label: web-project
    spec:
      containers:
        - image: loayghareeb/project
          name: container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
